# Generated by Django 3.2.16 on 2023-05-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cards_per_day', models.PositiveIntegerField(default=0, verbose_name='Кол-во')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_side', models.CharField(max_length=200, verbose_name='Лицо')),
                ('prompt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дефиниция')),
                ('back_side', models.CharField(max_length=200, verbose_name='Ответ')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('example', models.TextField(blank=True, verbose_name='Пример')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('next_use_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата след. показа')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Уровень')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.deck')),
            ],
        ),
    ]
