# Generated by Django 3.2.16 on 2023-05-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='core.customuser'),
            preserve_default=False,
        ),
    ]
