# Generated by Django 3.2.16 on 2023-07-06 16:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230704_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to=core.models.user_directory_path, width_field=100),
        ),
    ]
