# Generated by Django 3.2.16 on 2023-08-21 15:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path, validators=[core.models.Card.image_validator]),
        ),
    ]
