version: '3'

volumes:
  mysql_test:
  static:
  media:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # db:

  backend:
    build: ./backend/
    env_file: ./backend/decksapi/.env
    # depends_on:
      # - db
    volumes:
      - static:/backend_static
  frontend:
    build: ./frontend/
    # depends_on:
      # - db
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./nginx/
    ports:
      - 80:80
    # depends_on:
      # - db
    volumes:
      - ./specs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/app/media
