# Generated by Django 3.2.16 on 2023-10-04 10:04

import decks.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Deck description')),
                ('cards_per_day', models.PositiveIntegerField(default=10, verbose_name='Amount per day')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_side', models.CharField(max_length=200, verbose_name='Front')),
                ('prompt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Definition')),
                ('back_side', models.CharField(max_length=200, verbose_name='Answer')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to=decks.models.user_directory_path)),
                ('example', models.TextField(blank=True, verbose_name='Example')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('next_use_date', models.DateTimeField(auto_now_add=True, verbose_name='next appears date')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='level')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck')),
            ],
        ),
    ]
