# Generated by Django 3.2.16 on 2023-09-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsintag',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_used', to='news.news'),
        ),
        migrations.AlterField(
            model_name='newsintag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_used', to='news.tag'),
        ),
    ]
