name: Main Kitty workflow
on:
  push:
    branches:
      - kmikhail
jobs:
  backend_tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
          MYSQL_DATABASE: db
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8==6.0.0 flake8-isort==6.0.0
        pip install -r ./backend/requirements.txt
    - name: Test with flake8
      run: python -m flake8 backend/
    - name: backend tests
      env:
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
          MYSQL_DATABASE: db
          # Сервер БД запущен в Docker, но его порт проброшен на хост
          # Поэтому подключаемся к 127.0.0.1:5432
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
      run: |
        cd backend/
        python manage.py test